CREATE DATABASE DuAn1_QuanLyThuVien

CREATE TABLE NhanVien(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaNV VARCHAR(10) NOT NULL,
MatKhau VARCHAR(Max) NOT NULL,
HoTen NVARCHAR(50) NOT NULL,
NgaySinh DATE NOT NULL,
GioiTinh  NVARCHAR(50) NOT NULL,
DiaChi NVARCHAR(50) NOT NULL,
SDT NVARCHAR(50) NOT NULL,
TrangThai INT
)

CREATE TABLE DocGia(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaDocGia VARCHAR(10) NOT NULL,
HoTen NVARCHAR(50) NOT NULL,
NgaySinh DATE NOT NULL,
GioiTinh  NVARCHAR(50) NOT NULL,
DiaChi NVARCHAR(50) NOT NULL,
SDT NVARCHAR(50) NOT NULL,
)


CREATE TABLE TacGia(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaTacGia VARCHAR(10) NOT NULL,
TentacGia NVARCHAR(50) NOT NULL,
NgaySinh DATE NOT NULL,
GioiTinh  NVARCHAR(50) NOT NULL,
DiaChi NVARCHAR(50) NOT NULL,
ButDanh  NVARCHAR(50) NOT NULL
)

CREATE TABLE TheLoai(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaTheLoai VARCHAR(10) NOT NULL,
TenTheLoai NVARCHAR(50) NOT NULL,
)

CREATE TABLE NhaXuatBan(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaNhaXuatBan VARCHAR(10) NOT NULL,
TenNhaXuatBan NVARCHAR(50) NOT NULL,
DiaChi NVARCHAR(50) NOT NULL,
SDT NVARCHAR(50) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL,
WEBSITE NVARCHAR(50) NOT NULL,
)

CREATE TABLE Sach(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TenSach NVARCHAR(50) NOT NULL,
MaSach VARCHAR(10) NOT NULL,
MaISBN NVARCHAR(50) NOT NULL,
IDTacGia UNIQUEIDENTIFIER NOT NULL,
IDTheLoai UNIQUEIDENTIFIER NOT NULL,
IDNhaXuatBan UNIQUEIDENTIFIER NOT NULL,
NamXuatBan DATE NOT NULL,
Gia MONEY NOT NULL,
SoLuong INT NOT NULL,
SoTrang INT NOT NULL,
TinhTrangSach NVARCHAR(50)NOT NULL,
TrangThai INT,
FOREIGN KEY (IDTacGia) REFERENCES TacGia(ID),
FOREIGN KEY (IDTheLoai) REFERENCES TheLoai(ID),
FOREIGN KEY (IDNhaXuatBan) REFERENCES NhaXuatBan(ID),
)



CREATE TABLE PhieuYeuCauTTV(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
HoTen NVARCHAR(50) NOT NULL,
NgaySinh Date NOT NULL,
QueQuan NVARCHAR(50) NOT NULL,
GioiTinh  NVARCHAR(50) NOT NULL,
DiaChi NVARCHAR(50) NOT NULL,
SDT NVARCHAR(50) NOT NULL,
)

CREATE TABLE TheThuVien(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdDocGia UNIQUEIDENTIFIER NOT NULL,
MaTTV VARCHAR(10) NOT NULL,
NgayCap Date NOT NULL,
NgayHetHan Date,
GhiChu NVARCHAR(50) NOT NULL,
TrangThai INT NOT NULL,
FOREIGN KEY (IdDocGia) REFERENCES DocGia(ID),
)

CREATE TABLE PhieuMuon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdTTV UNIQUEIDENTIFIER NOT NULL,
MaPhieuMuon VARCHAR(10) NOT NULL,
TenDocGia NVARCHAR(50) NOT NULL,
DiaChiDocGia NVARCHAR(50) NOT NULL,
NgayMuon DATE NOT NULL,
NgayHenTra DATE NOT NULL,
GhiChu NVARCHAR(Max),
TienCoc MONEY,
FOREIGN KEY (IdTTV) REFERENCES TheThuVien(ID)
)

CREATE TABLE PhieuMuonChiTiet(
IdPhieuMuon UNIQUEIDENTIFIER NOT NULL,
IdSach UNIQUEIDENTIFIER NOT NULL,
MaPhieuMuon VARCHAR(10) NOT NULL,
MaSach VARCHAR(10) NOT NULL,
TenSach NVARCHAR(50) NOT NULL,
SoLuong INT,
SoTrang INT NOT NULL,
TinhTrangSach NVARCHAR(50)NOT NULL,
PRIMARY KEY(IdPhieuMuon,IdSach),
FOREIGN KEY (IdPhieuMuon) REFERENCES PhieuMuon(ID),
FOREIGN KEY (IdSach) REFERENCES Sach(ID),
)
CREATE TABLE PhieuTra(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IDPhieuMuon UNIQUEIDENTIFIER NOT NULL,
TenDocGia NVARCHAR(50) NOT NULL,
DiaChiDocGia NVARCHAR(50) NOT NULL,
NgayMuon DATE NOT NULL,
NgayHenTra DATE NOT NULL,
GhiChu NVARCHAR(Max),
TrangThai INT,
FOREIGN KEY (IdPhieuMuon) REFERENCES PhieuMuon(ID),
)

CREATE TABLE PhieuTraChiTiet(
IdPhieuTra UNIQUEIDENTIFIER NOT NULL,
IdSach UNIQUEIDENTIFIER NOT NULL,
MaSach VARCHAR(10) NOT NULL,TenSach NVARCHAR(50) NOT NULL,
SoLuong INT,
SoTrang INT NOT NULL,
TinhTrangSach NVARCHAR(50)NOT NULL,
PRIMARY KEY(IdPhieuTra,IdSach),
FOREIGN KEY (IdPhieuTra) REFERENCES PhieuTra(ID),
FOREIGN KEY (IdSach) REFERENCES Sach(ID),
)
CREATE TABLE PhieuDen(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaDen VARCHAR(10) NOT NULL,
IDNhanVien UNIQUEIDENTIFIER NOT NULL,
IDTTV UNIQUEIDENTIFIER NOT NULL,
LyDoPhat NVARCHAR(50),
SoTienPhat MONEY,
NgayPhat DATE,
FOREIGN KEY (IDNhanVien) REFERENCES NhanVien(ID),
FOREIGN KEY (IDTTV) REFERENCES TheThuVien(ID),
)

CREATE TABLE PhieuNopMuon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaPhieuNopMuon VARCHAR(10) NOT NULL,
IDNhanVien UNIQUEIDENTIFIER NOT NULL,
IDTTV UNIQUEIDENTIFIER NOT NULL,
LyDoNopMuon NVARCHAR(50),
SoTienPhat MONEY,
NgayPhat DATE,
FOREIGN KEY (IDNhanVien) REFERENCES NhanVien(ID),
FOREIGN KEY (IDTTV) REFERENCES TheThuVien(ID),
)